classes_views/clase3/urls.py
from django.conf.urls import url
from clase3 import views
from django.urls import path

app_name = 'clase3_app'

urlpatterns = [
	url('index',views.EscuelaListView.as_view(),name='list'),
	#url(r'^(?P<pk>[-\w]+)/$',views.EscuelaDetailView.as_view(),name='detalle'),
	path('<int:pk>/',views.EscuelaDetailView.as_view(),name='detalle'),
	path('create/',views.EscuelaCreateView.as_view(),name="create"),
	path('update/<int:pk>',views.EscuelaUpdateView.as_view(),name="update"),
	path('delete/<int:pk>',views.EscuelaDeleteView.as_view(),name="delete"),
]
#pk primary key of the school 
# co

classes_views/classes_views/urls.py
from django.contrib import admin
from django.urls import path, include
#from clase1 import views
from clase2 import views as views_clase2
from clase3 import views as views_clase3
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',views.index),   viejo
    #path('', views.CVBview.as_view()), # clase1
    #path('', views_clase2.IndexView.as_view()), #clase2
    path('',views_clase3.IndexView.as_view()),
    path('clase3/',include('clase3.urls',namespace='clase3_urls')),



]

classes_views/clase1/models.py
from django.db import models

# Create your models here.

classes_views/clase2/models.py
from django.db import models

classes_views/clase3/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Escuela(models.Model):
	name = models.CharField(max_length=128)
	principal = models.CharField(max_length=128)
	location =  models.CharField(max_length=128)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("clase3_app:detalle",kwargs={'pk':self.pk})

class Estudiante(models.Model):
	name = models.CharField(max_length=256)
	age = models.PositiveIntegerField()
	school = models.ForeignKey(Escuela,on_delete=models.CASCADE,related_name = 'students')

	def __str__(self):
		return self.name

classes_views/clase1/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponse
# Create your views here.
# antiguo   views por funcione

#def index(request):
#	return render(request,'index.html')

class CVBview(View):
	def get(self,request):
		return HttpResponse("CLASS BASED VIEWS ARE COOL")

classes_views/clase2/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView
# Create your views here.


class IndexView(TemplateView):
	template_name = 'clase2/index.html'
	# hay 2 tipos. el primero es *args, donde solo se inserta el valor (tuplas)    
	# kwargs donde se insertan de modo diccionario, pueden ser cuantos valores como se desee
	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		context['injectme'] = 'BASIC INJECTION'
		return context

classes_views/clase3/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView, ListView, DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse, reverse_lazy 
from . import models

# Create your views here.

class IndexView(TemplateView):
	template_name = 'clase3/index.html'

class EscuelaListView(ListView):
	# listView por defecto devuelve el nombre del objeto, en minusculas y agrega al final un _list
	#en este caso seria escuela_list
	#se puede cambiar, para poner otro nombre usando context_object_name
	context_object_name = 'escuelas'
	model  = models.Escuela
	template_name = 'clase3/escualeas_list.html'
	

class EscuelaDetailView(DetailView):
	model = models.Escuela
	# def get_context_data(self,**kwargs):
	# 	print("entra")
	# 	context = super().get_context_data(**kwargs)
	# 	#context = super().get_object_or_404(pk=kwargs['pk'])
	# 	context['pk_1'] = self.kwargs['pk']
	# 	return context

	context_object_name = "escuela_detalle"

	template_name = 'clase3/escuela_detail.html'

class EscuelaCreateView(CreateView):
	#recodar que por defecto context_object_name se hace con el nombre del model en minuscula
	# en este caso escuela
	# si se quiere cambiar se ha de usar la variable context_object_name = "loquesdea"
	#para poder llamarlo desde algun html (o el por defecto o cambiarlo con template_name)
	fields = ('name','principal','location')
	model = models.Escuela

class EscuelaUpdateView(UpdateView):
	#recodar que por defecto context_object_name se hace con el nombre del model en minuscula
	# en este caso escuela
	# si se quiere cambiar se ha de usar la variable context_object_name = "loquesdea"
	#para poder llamarlo desde algun html (o el por defecto o cambiarlo con template_name)
	
	fields = ('name','principal')
	model = models.Escuela

class EscuelaDeleteView(DeleteView):
	model = models.Escuela
	#recodar que por defecto context_object_name se hace con el nombre del model en minuscula
	# en este caso escuela
	# si se quiere cambiar se ha de usar la variable context_object_name = "loquesdea"
	#para poder llamarlo desde el html list
	#reverse_lazy te entregara la interface list con los valores actualisdos(sin el que has borrado)
	success_url = reverse_lazy('clase3_app:list')

classes_views/clase3/templates/clase3/clase3_base.html
<!DOCTYPE html>
<html>
<head>
	<title> This is a view per class</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<nav class = "navbar navbar-default navbar-static-top"> 
	<ul class = "nav navbar-nav">
		<li class = "navbar-item"><a class="navbar-brand" href="{% url 'clase3_app:list' %}">Escuelas</a></li>
		<li class = "navbar-item" ><a class="navbar-link" href="{% url 'admin:index'  %}">Admin </a></li>
		<li><a href="#"></a></li>
	</ul>
</nav>

<div class = "container">
{% block body_block %}

{% endblock %}
</div>
</body>
</html>

classes_views/clase3/templates/clase3/escualeas_list.html
{% extends "clase3/clase3_base.html" %}

{% block body_block %}

<h1>Esta es la lista de escuelas</h1>

<ol>
	{% for school in escuelas %}
	<h2>
		<li>
			<a href="{{ school.id }}">{{ school.name }}</a>
		</li>
	</h2>
	{% endfor %}
</ol>
<p><a class="btn" href="{% url 'clase3_app:create' %}">Crear Una Escuela</a></p>

{% endblock %}

classes_views/clase3/templates/clase3/escuela_confirm_delete.html
{% extends 'clase3/clase3_base.html' %}

{% block body_block %}

<h1> BOrrar {{ escuela.name }}?</h1>

<form method = "POST">
	{% csrf_token %}
	<input type="submit" class="btn btn-danger" value="Delete">
	<!-- primeoro ponemos el link para borrar una escuela pero pasamos el primary
	key pk para que sepa cual escuela es la que hay que borrar -->
	<a href="{% url 'clase3_app:detalle' pk=escuela.pk %}">Cancel</a>

</form>

{% endblock %}

classes_views/clase3/templates/clase3/escuela_detail.html
{% extends "clase3/clase3_base.html" %}

{% block body_block %}

<div class="jumbotron">
	<h1> Los detalles de la escuela aqui </h1>
	<h2>Detalles de Escuela:</h2>
	<p>Nombre: {{ escuela_detalle.name }}</p>
	<p>Director: {{escuela_detalle.principal}}	</p>
	<p>Ubicacion: {{ escuela_detalle.location }}</p>

	<h3>Estudiantes en esta escuela: </h3>
    <!-- el escuela_detalle es la variable, el students viene del modelo y el fetch all -->
	{% for estudiando in escuela_detalle.students.all %}
	<p>{{ estudiando.name }}, quien tiene {{ estudiando.age}} anyos </p>
	{% endfor %}
</div>
<div class=container>
	<!-- primeoro ponemos el link para acutalizar una escuela pero pasamos el primary
		key pk para que sepa cual escuela es la que hay que actualizar -->
	<p><a class="btn btn-warning" href="{% url 'clase3_app:update' pk=escuela_detalle.pk %}">Actualizar campos escuela</a></p>
	<p><a class="bton btn-danger" href="{% url 'clase3_app:delete' pk=escuela_detalle.pk %}" >Borrar escuela</a></p>
</div>

{% endblock %}

classes_views/clase3/templates/clase3/escuela_form.html
{% extends "clase3/clase3_base.html" %}

{% block body_block %}

<h1>
{% if not form.instance.pk  %}
 Create Escuela
{% else %}
Actualiza Escuela
{% endif %}
</h1>

<div class="container">
	<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" name="btn btn-primary" value="Submit">
	</form>
</div>



{% endblock %}

classes_views/clase3/templates/clase3/index.html
{% extends "clase3/clase3_base.html" %}

{% block body_block %}

<div class = "jumbotron">
<h1>Hello world! Index Page Home</h1>
<h2>This is a variable inserted using classes : {{  injectme }}</h2>
</div>

{% endblock %}

classes_views/templates/clase1/base.html
<!DOCTYPE html>
<html>
<head>
	<title> This is a view per class</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<nav class = "navbar navbar-default navbar-static-top"> 
	<ul class = "nav navbar-nav">
		<li class = "navbar-item"><a class="navbar-brand" href="{% url 'clase3:list' %}">Escuelas</a></li>
		<li class = "navbar-item" ><a class="navbar-link" href="{% url 'admin:index'  %}">Admin </a></li>
		<li><a href="#"></a></li>
	</ul>
</nav>

<div class = "container">
{% block body_block %}

{% endblock %}
</div>
</body>
</html>

classes_views/templates/clase1/index.html
{% extends "clase1/base.html" %}

{% block body_block %}

<div class="jumbotron">
<h1>Hello world! Index Page Home</h1>
</div>
{% endblock %}

classes_views/templates/clase2/base.html
<!DOCTYPE html>
<html>
<head>
	<title> This is a view per class</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<div class = "container">
{% block body_block %}

{% endblock %}
</div>
</body>
</html>

classes_views/templates/clase2/index.html
{% extends "clase2/base.html" %}

{% block body_block %}

<h1>Hello world! Index Page Home</h1>
<h2>This is a variable inserted using classes : {{  injectme }}</h2>

{% endblock %}