Final/Final/urls.py
from django.contrib import admin
from django.urls import path,include
from My_App import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('My_App/',include('My_App.urls')),
    path('logout/',views.user_logout,name='user_logout'),
    path('special/',views.special,name='special'),
]

Final/My_App/urls.py
from django.conf.urls import url
from My_App import views

#TEMPLATE URLS

app_name='My_App'

urlpatterns = [
	url('register/', views.register,name='register'),
	url('user_login/', views.user_login,name='user_login'),
]

Final/My_App/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

	user = models.OneToOneField(User,on_delete=models.CASCADE)    #para evitar replicar usuarios creados. El perfil deriva del Modelo User

	#aditional classess
	portfolio_site = models.URLField(blank=True)   #puede no ser rellenada
	#subida de fotos
	profile_pic = models.ImageField(upload_to = 'profile_pics',blank=True)

	def __str__(self):
		return  self.user.username

Final/My_App/forms.py
from django import forms
from django.contrib.auth.models import User
from My_App.models import UserProfileInfo

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())  # el widget permitira guarada la password sin que se vea
    # heredamos la clase de usuario por defecto de Django
	class Meta():
		model = User
		fields = ('username','email','password')    # asi incluimos solo los campos que queremos.  Tambien existe opcion __all__ para cogerlos todos
		# o tambien exioste la opcion exclude = ['param1','param2']

class UserProfileInfoForm(forms.ModelForm):
	#heredamos el modelo que hemos creado en models.py
	class Meta():
		model  = UserProfileInfo
		fields = ('portfolio_site','profile_pic')

Final/My_App/views.py
from django.shortcuts import render
from My_App.forms import UserForm,UserProfileInfoForm
# Create your views here. ###################
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
	return render(request,'My_App/index.html')


def register(request):
	registered = False

	if request.method == "POST": 
		user_form  = UserForm(data=request.POST)  #recuperamos los datos del formuladio
		profile_form = UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			#guardamos la informacion de registro e usuario
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			#verificamos si la info del perfil es correcta
			profile = profile_form.save(commit=False)   
			profile.user = user  
			# si hay foro?
			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']
			profile.save()
			registered = True
		else:
			print(user_form.errors,profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()
	print(registered)
	return render(request, 'My_App/registration.html', { 'user_form':user_form,
														'profile_form':profile_form,
														'registered':registered})

def user_login(request):
	if request.method == 'POST':
		#recuperar del formuolatio los campos username y passweord
		username = request.POST.get('username')
		password = request.POST.get('password')
		print(username,password)
		user = authenticate(request,username=username,password=password)
		print(str(user))
		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))
			else:
				return HttpResponse("Cuenta no ACTIVA")
		else:
			print("Fallo de login")
			print("Username: {} and password {} ".format(username,password))
			return HttpResponse("Invalid logind details!!!!!")
	else:
		return render(request,'My_App/login.html')

# @ el login required es un decorador que hace que para que un usuario haga logout, necesariamente necesita necesita previamente estar loggeado
@login_required     
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))

# otro ejemplo:  Mostrar una pagina especial unicamne5te si se esta loggeado
@login_required
def special(request):
	return HttpResponse("efectivamente, estas loggeado")

Final/templates/My_App/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">	<title></title>
</head>
<body>
	<div class = container>
	<nav class='navbar navbar-expand-lg fixed-top'>	
		<div class="container">
			<ul class="navbar-nav">
				<li class = "nav-item"><a class="navbar-brand" href="{% url 'index' %}"> DJANGO</a></li>
				<li class = "nav-item"><a class="nav-link" href="{% url 'admin:index' %}"> ADMIN </a></li>
				<li class = "nav-item"><a class="nav-link" href="{% url 'My_App:register' %}"> Register</a></li>
				{% if user.is_authenticated %}
				<li class = "nav-item"><a class="nav-link" href="{% url 'user_logout' %}">Logout</a></li>
				{% else %}
				<li class = "nav-item"><a class="nav-link" href="{% url 'My_App:user_login' %}">Login</a></li>
				{% endif %}
			</ul>		
		</div>
	</nav>
	</div>
	<div></div>

	<div class="container">

		{% block body_block %}
		
		{% endblock %}
	</div>
<!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> -->
</body>
</html>

Final/templates/My_App/index.html
{% extends "My_App/base.html" %}
{% block body_block %}

<div class="jumbotron">
	<h1>Django 5 Login</h1>
</div>

{% endblock %}

Final/templates/My_App/login.html
{% extends 'My_App/base.html' %}
{% block body_block %}

<div class="jumbotron">
	<h1>Please Login</h1>
	<form action = "{% url 'My_App:user_login' %}" method="POST">
		{% csrf_token %}

		<label for="username">Username: </label>
		<input type="text" name="username" placeholder="Insertar Username">

		<label for="password">Password: </label>
		<input type="password" name="password">

		<input type="submit" name="" value="Login">
		
	</form>
		

{% endblock %}

Final/templates/My_App/registration.html
<!DOCTYPE html>
{% extends "My_App/base.html" %}
{% load static %}
{% block body_block %}
<div class=jumbotron>
	{% if registered %}
		<h1> Thank you for registering!</h1>
	{% else %}
	<h1>Register Here</h1>
	<h3> Fill Out the form : </h3>
	<form  enctype="multipart/form-data" method="POST">
		{% csrf_token %}
		{{ user_form.as_p }}
		{{  profile_form.as_p }}
		<input type="submit" name="" value="Register">
	</form>
	{% endif %}
</div>
{% endblock %}